name: Build
run-name: Nightly build
on: [push]
jobs:
  build-latest:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
    - name: Setup Node
      uses: actions/setup-node@v3
      with:
        node-version: 20
    - name: install wine
      id: wine_install
      run: |
        sudo apt install wine64
        sudo dpkg --add-architecture i386
        sudo apt update
        sudo apt install wine32
        echo "WINE_PATH=$(which wine64)" >> $GITHUB_OUTPUT
    - run: npm i -g pnpm
    - run: pnpm i
    - run: pnpm build -w -p always
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

